# Generated by Django 4.2.7 on 2025-08-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
