# Generated by Django 4.2.7 on 2025-08-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_verification_tokens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='users_email_token_76af91_idx',
            old_name='users_emailv_token_8b2b8b_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='users_email_user_id_0476c8_idx',
            old_name='users_emailv_user_id_9c8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_token_766a81_idx',
            old_name='users_passwor_token_7a1a1a_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_5ee9a9_idx',
            old_name='users_passwor_user_id_8b2b2b_idx',
        ),
    ]
