# Generated by Django 4.2.7 on 2025-08-20 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_verify_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidatedRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('invalidated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalidated_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['token_hash'], name='users_inval_token_h_61496a_idx'), 
                    models.Index(fields=['user', 'invalidated_at'], name='users_inval_user_id_b00c2e_idx'), 
                    models.Index(fields=['expires_at'], name='users_inval_expires_0411f6_idx')
                ],
            },
        ),
    ]
